[custom]


; ===== 内网最高优先级直连 =====
ruleset=⚡ 直连,[]GEOIP,private,no-resolve
ruleset=⚡ 直连,[]GEOSITE,private


; 2. 你自己的强制直连 / 强制代理
; ruleset=直连,xxx
; ruleset=国外网站,xxx


; 3. 国内例外
ruleset=🇬 GoogleCN,[]GEOSITE,google-cn

; ===== 国内游戏直连 =====

ruleset=⚡ 直连,[]GEOSITE,category-games@cn
ruleset=⚡ 直连,[]GEOSITE,steam@cn

; ===== 游戏下载直连 =====
ruleset=⚡ 直连,[]GEOSITE,category-game-platforms-download

; ===== BT Tracker 相关域名直连 =====

ruleset=⚡ 直连,[]GEOSITE,category-public-tracker


; ===== 苹果细分 =====

ruleset=📺 AppleTV,[]GEOSITE,apple-tvplus
ruleset=📺 AppleTV,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/AppleTV/AppleTV.yaml,28800
ruleset=🍏 AppleProxy,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/AppleNews/AppleNews.yaml,28800
ruleset=🍎 AppleDirect,[]GEOSITE,apple-cn
ruleset=🍏 AppleProxy,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/AppleProxy/AppleProxy.yaml,28800
ruleset=🍏 AppleProxy,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/iCloudPrivateRelay/iCloudPrivateRelay.yaml,28800
ruleset=🍎 AppleDirect,[]GEOSITE,apple

; ===== 社媒细分 =====

;Talkatone可能用用到，单独细分出来
ruleset=📞 Talkatone,[]GEOSITE,talkatone
;即时通讯包括了 Telegram/WhatsApp/Line 等海外主流即时通讯软件域名
ruleset=💬 即时通讯,[]GEOSITE,category-communication
;TikTok细分
ruleset=🎶 TikTok,[]GEOSITE,tiktok
;社交媒体包括了 Twitter(X)/Facebook/Instagram 等海外主流社交媒体
ruleset=🌐 社交媒体,[]GEOSITE,category-social-media-!cn



; ===== AI细分 =====
ruleset=🤖 ChatGPT,[]GEOSITE,openai
ruleset=💾 OneDrive,[]GEOSITE,onedrive
ruleset=🤖 Copilot,[]GEOSITE,bing
ruleset=🤖 AI服务,[]GEOSITE,category-ai-!cn
ruleset=👦 GitHub,[]GEOSITE,github
;测速工具包括 SpeedTest 等主流测速工具域名
ruleset=🚀 测速工具,[]GEOSITE,category-speedtest
;要直连的steam已经前置直连，这里用来访问其他需要代理的服务
ruleset=🎮 Steam,[]GEOSITE,steam
ruleset=📺 YouTube,[]GEOSITE,youtube
ruleset=Ⓜ️ 微软,[]GEOSITE,microsoft
ruleset=📢 谷歌FCM,[]GEOSITE,googlefcm
ruleset=🇬 Google,[]GEOSITE,google
ruleset=🎥 Netflix,[]GEOSITE,netflix
ruleset=🎥 DisneyPlus,[]GEOSITE,disney
ruleset=🎥 HBO,[]GEOSITE,hbo
ruleset=🎥 PrimeVideo,[]GEOSITE,primevideo
;Emby 包括主流 Emby 服务相关域名
ruleset=🎥 Emby,[]GEOSITE,category-emby
ruleset=🎻 Spotify,[]GEOSITE,spotify
ruleset=📺 Bahamut,[]GEOSITE,bahamut
ruleset=🎮 游戏平台,[]GEOSITE,category-games
ruleset=📺 国外媒体,[]GEOSITE,category-entertainment
ruleset=⏬ PT站点,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PrivateTracker/PrivateTracker.yaml,86400
ruleset=💳 PayPal,[]GEOSITE,paypal
ruleset=🛒 国外电商,[]GEOSITE,category-ecommerce


; ===== 部分IP兜底 =====

ruleset=💬 即时通讯,[]GEOIP,telegram,no-resolve
ruleset=🌐 社交媒体,[]GEOIP,twitter,no-resolve
ruleset=🌐 社交媒体,[]GEOIP,facebook,no-resolve
ruleset=🇬 Google,[]GEOIP,google,no-resolve
ruleset=🎥 Netflix,[]GEOIP,netflix,no-resolve
;由于 OpenClash 使用的大陆白名单收录不全，此处留有 geosite:cn 作为国内域名兜底


; ===== GFW默认代理兜底 =====

ruleset=✋ 手动选择,clash-domain:https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt,86400

; ===== 代理域名兜底 =====

ruleset=✋ 手动选择,clash-domain:https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt,86400

; ===== ⚡ 直连兜底 =====
ruleset=⚡ 直连,clash-domain:https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt,86400
ruleset=⚡ 直连,[]GEOSITE,cn
ruleset=⚡ 直连,[]GEOIP,CN,no-resolve

; ===== 非标端口，高优先级服务规则之后，地理兜底规则之前 =====

ruleset=❌ 非标端口,clash-classic:https://raw.githubusercontent.com/J1ngyang/CutomFullRules/refs/heads/main/NonStandardPort.yaml,86400

;国内冷门域名会命中漏网之鱼，如影响使用，请设置漏网之鱼直连
;漏网之鱼直连时，无法通过 DNS 泄露测试，但是并不存在泄露
ruleset=🐟 漏网之鱼,[]FINAL



; ===== 策略组 =====

; ===== 基础控制 =====
custom_proxy_group=✋ 手动选择`select`.*
custom_proxy_group=⚡ 直连`select`[]DIRECT


; ===== Apple 相关 =====
custom_proxy_group=📺 AppleTV`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🍏 AppleProxy`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🍎 AppleDirect`select`[]⚡ 直连`[]✋ 手动选择`.*


; ===== AI / 开发 / 生产力 =====
custom_proxy_group=🤖 ChatGPT`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🤖 Copilot`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🤖 AI服务`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=👦 GitHub`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=💾 OneDrive`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=Ⓜ️ 微软`select`[]✋ 手动选择`[]⚡ 直连`.*


; ===== Google 相关 =====
custom_proxy_group=🇬 GoogleCN`select`[]⚡ 直连`[]✋ 手动选择`.*
custom_proxy_group=📺 YouTube`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=📢 谷歌FCM`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🇬 Google`select`[]✋ 手动选择`[]⚡ 直连`.*


; ===== 即时通讯 / 社交媒体 =====
custom_proxy_group=📞 Talkatone`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=💬 即时通讯`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🎶 TikTok`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🌐 社交媒体`select`[]✋ 手动选择`[]⚡ 直连`.*


; ===== 流媒体 =====
custom_proxy_group=🎥 Netflix`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🎥 DisneyPlus`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🎥 HBO`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🎥 PrimeVideo`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🎥 Emby`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🎻 Spotify`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=📺 Bahamut`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=📺 国外媒体`select`[]✋ 手动选择`[]⚡ 直连`.*


; ===== 游戏 / 下载 / PT =====
custom_proxy_group=🎮 Steam`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🎮 游戏平台`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=⏬ PT站点`select`[]✋ 手动选择`[]⚡ 直连`.*


; ===== 金融 / 电商 / 工具 =====
custom_proxy_group=💳 PayPal`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🛒 国外电商`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🚀 测速工具`select`[]✋ 手动选择`[]⚡ 直连`.*


; ===== 特殊流量 / 兜底 =====
custom_proxy_group=❌ 非标端口`select`[]✋ 手动选择`[]⚡ 直连`.*
custom_proxy_group=🐟 漏网之鱼`select`[]✋ 手动选择`[]⚡ 直连`.*

enable_rule_generator=true
overwrite_original_rules=true
